# Generated by Django 3.1.7 on 2021-04-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addinfo',
            name='state',
        ),
    ]
