# Generated by Django 3.1.7 on 2021-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.RemoveField(
            model_name='addinfo',
            name='design',
        ),
        migrations.RemoveField(
            model_name='addinfo',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='addinfo',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='addinfo',
            name='uname',
        ),
        migrations.AddField(
            model_name='addinfo',
            name='blo1',
            field=models.CharField(default='blog', max_length=50),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='domain',
            field=models.CharField(default='domain', max_length=50),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='email',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='loc1',
            field=models.CharField(default='location', max_length=50),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='proj',
            field=models.CharField(default='project', max_length=50),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='tech',
            field=models.CharField(default='techology', max_length=30),
        ),
    ]
