# Generated by Django 3.1.7 on 2021-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210417_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfo',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
    ]
