# Generated by Django 3.1.7 on 2021-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210417_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addinfo',
            name='developer_rating',
        ),
        migrations.RemoveField(
            model_name='addinfo',
            name='score',
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='blo1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='domain',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='loc1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='proj',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='tech',
            field=models.CharField(max_length=30),
        ),
    ]
