# Generated by Django 3.1.7 on 2021-04-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210417_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinfo',
            name='developer_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
