# Generated by Django 3.1.7 on 2021-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210417_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfo',
            name='developer_rating',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='score',
            field=models.CharField(max_length=50),
        ),
    ]
