# Generated by Django 3.1.7 on 2021-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210417_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfo',
            name='developer_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addinfo',
            name='score',
            field=models.FloatField(),
        ),
    ]
