# Generated by Django 3.1.7 on 2021-04-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210417_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinfo',
            name='blog_rating',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='addinfo',
            name='project_rating',
            field=models.FloatField(default=10),
        ),
    ]
